package com.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBDocument
//@JsonInclude(JsonInclude.Include.NON_NULL)
@DynamoDBTable(tableName = "UserHistoryy")
public class UserHistory {

    /*@DynamoDBAttribute
    private String eventType;*/

    @DynamoDBAttribute
    private String sourceType;

    @DynamoDBAttribute
    private FieldName fieldName;

    @DynamoDBIndexRangeKey(localSecondaryIndexName = "eventTimeStamp-index")
    private String eventTimeStamp;

    @DynamoDBAutoGeneratedKey
    @DynamoDBRangeKey
    private String uuId;

    @DynamoDBAttribute
    private String redId;

    @DynamoDBHashKey
    private String personId;

    @DynamoDBAttribute
    private String newVale;

    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private String userAccountId;

    @DynamoDBAttribute
    private String details;

    @DynamoDBAttribute
    private List<Event> event;

}
